# Generated by Django 5.1.2 on 2025-09-03 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyality', '0002_loyalty_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loyaltypointsledger',
            index=models.Index(fields=['profile', '-created_at'], name='loyality_lo_profile_255165_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltypointsledger',
            index=models.Index(fields=['type', '-created_at'], name='loyality_lo_type_1d8220_idx'),
        ),
    ]
