# Generated by Django 5.1.2 on 2025-08-28 03:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('subtotal_cents', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tip_cents', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_cents', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cents', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivery', models.CharField(default='DINE_IN', help_text='One of: "DINE_IN", "UBER_EATS", "DOORDASH"', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='created', max_length=12)),
                ('stripe_session_id', models.CharField(blank=True, max_length=120)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=120)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('unit_amount_cents', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('line_total_cents', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.order')),
            ],
            options={
                'ordering': ['order_id', 'id'],
            },
        ),
    ]
