# Generated by Django 5.1.2 on 2025-09-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepaymentintent',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID for saved payment methods', max_length=255),
        ),
    ]
