# Generated by Django 5.1.2 on 2025-09-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_stripepaymentintent_stripe_customer_id'),
        ('payments', '0003_intent_link_canonical_order'),
    ]

    operations = [
    ]
