# Generated by Django 5.1.2 on 2025-09-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_merge_20250903_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='source_order',
        ),
        migrations.RemoveField(
            model_name='stripepaymentintent',
            name='order_ref',
        ),
    ]
