# Generated by Django 5.1.2 on 2025-08-29 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('table_type', models.CharField(choices=[('dining', 'Dining Table'), ('bar', 'Bar Table'), ('outdoor', 'Outdoor Table'), ('private', 'Private Dining')], default='dining', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_tables', to='core.location')),
            ],
            options={
                'ordering': ['location_id', 'table_number'],
                'unique_together': {('location', 'table_number')},
            },
        ),
    ]
