# Generated by Django 5.1.2 on 2025-09-03 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_soft_drop_core_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Name of the model that was changed', max_length=100)),
                ('object_id', models.CharField(help_text='ID of the object that was changed', max_length=100)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], help_text='Type of action performed', max_length=10)),
                ('at', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('diff', models.JSONField(default=dict, help_text='JSON object containing the changes made')),
                ('by_user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['model_name', '-at'], name='core_auditl_model_n_749993_idx'), models.Index(fields=['object_id', '-at'], name='core_auditl_object__cd9e45_idx'), models.Index(fields=['by_user', '-at'], name='core_auditl_by_user_f2763d_idx'), models.Index(fields=['action', '-at'], name='core_auditl_action_f262f3_idx'), models.Index(fields=['model_name', 'object_id', '-at'], name='core_auditl_model_n_a92279_idx')],
            },
        ),
    ]
