# Generated by Django 5.1.2 on 2025-09-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyality', '0004_indexes_and_data_copy'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loyaltypointsledger',
            name='ll_profile_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='loyaltypointsledger',
            name='ll_type_created_idx',
        ),
    ]
