# Generated by Django 5.1.2 on 2025-08-28 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.location')),
            ],
            options={
                'ordering': ['location_id', 'table_number'],
                'unique_together': {('location', 'table_number')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=120)),
                ('guest_phone', models.CharField(blank=True, max_length=40)),
                ('party_size', models.PositiveIntegerField(default=2)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reservation_date', models.DateField(editable=False)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('completed', 'Completed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.location')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.table')),
            ],
            options={
                'ordering': ['-start_time', '-id'],
                'indexes': [models.Index(fields=['location', 'table', 'start_time'], name='reservation_locatio_c28706_idx'), models.Index(fields=['location', 'start_time', 'end_time'], name='reservation_locatio_f37d97_idx'), models.Index(fields=['reservation_date'], name='reservation_reserva_29d2e6_idx')],
            },
        ),
    ]
