# Generated by hand – additive
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationHold",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, auto_created=True, verbose_name="ID")),
                ("party_size", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(max_length=16, choices=[("PENDING", "Pending"), ("CONFIRMED", "Confirmed"), ("EXPIRED", "Expired")], default="PENDING", db_index=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name="reservation_hold", to="orders.order")),
                ("table", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="holds", to="reservations.table")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reservation_holds", to="accounts.user")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["table", "status", "expires_at"], name="reservations_hold_idx"),
                ],
            },
        ),
    ]
