# Generated by Django 5.1.2 on 2025-08-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservationhold'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationHold',
        ),
    ]
