# Generated by Django 5.1.2 on 2025-09-03 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_deposit_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_created_54d651_idx',
            old_name='reservation_created_by_status_idx',
        ),
    ]
