# Generated by Django 5.1.2 on 2025-09-03 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_migrate_from_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest_phone',
            field=models.CharField(blank=True, help_text='Guest phone number', max_length=40, validators=[django.core.validators.RegexValidator(message='Phone number must be valid. Use digits with optional + (7-15 digits).', regex='^[\\+]?[1-9]?[0-9]{7,15}$')]),
        ),
    ]
