# Generated by hand – additive and safe
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rank",
            field=models.CharField(
                max_length=16,
                choices=[
                    ("BRONZE", "Bronze"),
                    ("SILVER", "Silver"),
                    ("GOLD", "Gold"),
                    ("PLATINUM", "Platinum"),
                ],
                default="BRONZE",
                db_index=True,
            ),
        ),
    ]
