# Generated by Django 5.1.2 on 2025-08-28 10:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Extra',
                'verbose_name_plural': 'Order Extras',
                'indexes': [models.Index(fields=['order', 'name'], name='engagement__order_i_5c72b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PendingTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Tip',
                'verbose_name_plural': 'Pending Tips',
                'indexes': [models.Index(fields=['user', 'created_at'], name='engagement__user_id_986003_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReservationHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_holds', to='orders.order')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='reservations.table')),
            ],
            options={
                'verbose_name': 'Reservation Hold',
                'verbose_name_plural': 'Reservation Holds',
                'indexes': [models.Index(fields=['table', 'status'], name='engagement__table_i_bbf575_idx'), models.Index(fields=['expires_at'], name='engagement__expires_b60989_idx')],
            },
        ),
        migrations.CreateModel(
            name='TipLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_ledgers', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tip Ledger Entry',
                'verbose_name_plural': 'Tip Ledger',
                'indexes': [models.Index(fields=['user'], name='engagement__user_id_3c7335_idx'), models.Index(fields=['order'], name='engagement__order_i_c724ce_idx'), models.Index(fields=['created_at'], name='engagement__created_f837d9_idx')],
            },
        ),
    ]
