# Generated by Django on 2025-08-27
from __future__ import annotations

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "__first__"),
        ("reservations", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderExtras",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("meta", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="extras", to="orders.order")),
            ],
            options={
                "verbose_name": "Order Extra",
                "verbose_name_plural": "Order Extras",
            },
        ),
        migrations.CreateModel(
            name="TipLedger",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tip_ledgers", to="orders.order")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Tip Ledger Entry",
                "verbose_name_plural": "Tip Ledger",
            },
        ),
        migrations.CreateModel(
            name="ReservationHold",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("CONFIRMED", "Confirmed"), ("EXPIRED", "Expired")], default="PENDING", max_length=16)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reservation_holds", to="orders.order")),
                ("table", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="holds", to="reservations.table")),
            ],
            options={
                "verbose_name": "Reservation Hold",
                "verbose_name_plural": "Reservation Holds",
            },
        ),
        migrations.AddIndex(
            model_name="orderextras",
            index=models.Index(fields=["order", "name"], name="engagement_o_order_i_3b5b92_idx"),
        ),
        migrations.AddIndex(
            model_name="tipledger",
            index=models.Index(fields=["user"], name="engagement_t_user_id_2e6e9c_idx"),
        ),
        migrations.AddIndex(
            model_name="tipledger",
            index=models.Index(fields=["order"], name="engagement_t_order_i_43c4a9_idx"),
        ),
        migrations.AddIndex(
            model_name="tipledger",
            index=models.Index(fields=["created_at"], name="engagement_t_created_3a8b3a_idx"),
        ),
        migrations.AddIndex(
            model_name="reservationhold",
            index=models.Index(fields=["table", "status"], name="engagement_r_table_i_0e7f1e_idx"),
        ),
        migrations.AddIndex(
            model_name="reservationhold",
            index=models.Index(fields=["expires_at"], name="engagement_r_expires__6a4d8e_idx"),
        ),
    ]
