# Generated by Django on 2025-08-27
from __future__ import annotations

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingTip",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pending_tips", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Pending Tip",
                "verbose_name_plural": "Pending Tips",
            },
        ),
        migrations.AddIndex(
            model_name="pendingtip",
            index=models.Index(fields=["user", "created_at"], name="engagement_p_user_id__b9a524_idx"),
        ),
    ]
