# Generated by Django 5.1.2 on 2025-09-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_soft_drop_inventory_table'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tableasset',
            new_name='inventory_t_conditi_326363_idx',
            old_name='inventory_t_condition_idx',
        ),
        migrations.RenameIndex(
            model_name='tableasset',
            new_name='inventory_t_created_ff536f_idx',
            old_name='inventory_t_created_at_idx',
        ),
        migrations.RemoveField(
            model_name='table',
            name='core_table',
        ),
        migrations.AlterField(
            model_name='tableasset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
