# Generated by Django 5.1.2 on 2025-09-02 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('subtotal_cents', models.PositiveIntegerField(default=0)),
                ('tip_cents', models.PositiveIntegerField(default=0)),
                ('discount_cents', models.PositiveIntegerField(default=0)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], default='evening', max_length=16)),
                ('staff', models.CharField(blank=True, help_text='Shift lead or cashier', max_length=120)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'shift', '-id'],
                'unique_together': {('date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('SYSTEM', 'System Action')], help_text='Type of action performed', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('model_name', models.CharField(blank=True, help_text='Name of the affected model', max_length=100)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the affected object', max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON representation of field changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('request_path', models.CharField(blank=True, help_text='Request path/URL', max_length=500)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', help_text='Severity level of the action', max_length=10)),
                ('category', models.CharField(blank=True, help_text='Category for grouping similar actions', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='reports_aud_user_id_ea3244_idx'), models.Index(fields=['action', '-created_at'], name='reports_aud_action_3dc273_idx'), models.Index(fields=['content_type', 'object_id'], name='reports_aud_content_a97ebc_idx'), models.Index(fields=['severity', '-created_at'], name='reports_aud_severit_e0c63c_idx'), models.Index(fields=['category', '-created_at'], name='reports_aud_categor_90332f_idx'), models.Index(fields=['ip_address', '-created_at'], name='reports_aud_ip_addr_6bd8d1_idx')],
            },
        ),
    ]
