# Generated by Django 5.1.2 on 2025-08-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('subtotal_cents', models.PositiveIntegerField(default=0)),
                ('tip_cents', models.PositiveIntegerField(default=0)),
                ('discount_cents', models.PositiveIntegerField(default=0)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], default='evening', max_length=16)),
                ('staff', models.CharField(blank=True, help_text='Shift lead or cashier', max_length=120)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'shift', '-id'],
                'unique_together': {('date', 'shift')},
            },
        ),
    ]
