# Generated by Django 5.1.2 on 2025-08-27 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_is_active'),
        ('reports', '0004_fix_user_tip_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTipAggregate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='tip_aggregate', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=150)),
                ('rank', models.CharField(max_length=16)),
                ('total_tip', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_tip', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_tip', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_tip_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Tips (Aggregate)',
                'verbose_name_plural': 'User Tips (Aggregate)',
                'db_table': 'reports_user_tip_agg',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='shiftreport',
            name='location',
        ),
        migrations.RemoveField(
            model_name='shiftreport',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailySales',
        ),
        migrations.DeleteModel(
            name='ShiftReport',
        ),
    ]
