# Generated by Django 5.1.2 on 2025-09-26 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_cart_source_alter_order_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, default='', max_length=20)),
                ('event', models.CharField(blank=True, default='', max_length=64)),
                ('success', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('UBEREATS', 'Uber Eats'), ('DOORDASH', 'DoorDash')], db_index=True, max_length=20)),
                ('external_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(db_index=True, default='pending', max_length=32)),
                ('last_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_refs', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'status'], name='integration_provide_553e25_idx')],
                'unique_together': {('provider', 'external_id')},
            },
        ),
    ]
