# Generated by Django 5.1.2 on 2025-09-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('UBEREATS', 'Uber Eats'), ('DOORDASH', 'DoorDash'), ('GRUBHUB', 'Grubhub')], db_index=True, max_length=20)),
                ('restaurant_id', models.CharField(db_index=True, max_length=64)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['platform', 'revoked'], name='integration_platfor_531a7c_idx'), models.Index(fields=['platform', 'expires_at'], name='integration_platfor_b8dccd_idx')],
                'unique_together': {('platform', 'restaurant_id')},
            },
        ),
    ]
