# Generated by Django 5.1.2 on 2025-09-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='Additional images for gallery display', null=True),
        ),
    ]
