# Generated by Django 5.1.2 on 2025-09-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderExtra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'orders_extras_orderextra',
                'managed': False,
            },
        ),
    ]
