# Generated by Django 5.1.2 on 2025-09-02 04:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Pickup/Delivery'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], help_text='Previous order status', max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Pickup/Delivery'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], help_text='New order status', max_length=20)),
                ('change_reason', models.TextField(blank=True, help_text='Reason for status change', max_length=500)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the status change', max_length=1000)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user making the change', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string for audit purposes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the status change')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the status change occurred')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the status change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Order being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='orders_orde_order_i_ca028d_idx'), models.Index(fields=['new_status', '-created_at'], name='orders_orde_new_sta_aa82c2_idx'), models.Index(fields=['changed_by', '-created_at'], name='orders_orde_changed_609ee6_idx'), models.Index(fields=['previous_status', 'new_status'], name='orders_orde_previou_3deb59_idx')],
            },
        ),
    ]
