# Generated by Django 5.1.2 on 2025-09-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('admin', 'Admin'), ('waiter', 'Waiter')], default='web', help_text='Cart creation source (web, mobile, admin, waiter)', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('admin', 'Admin'), ('waiter', 'Waiter')], default='web', help_text='Order creation source (web, mobile, admin, waiter)', max_length=50),
        ),
    ]
