name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Minimal environment for Django to boot
      DJANGO_SECRET_KEY: test-secret
      ENVIRONMENT: development
      # Ensure SQLite and non-HTTPS features are allowed for tests
      SECURE_SSL_REDIRECT: "0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django pytest-cov factory_boy freezegun coverage

      - name: Django check + migrate
        run: |
          python manage.py check --deploy --fail-level WARNING || true
          python manage.py migrate --noinput

      - name: Run tests with coverage
        run: |
          pytest -q

      - name: Enforce 95% coverage on money modules
        run: |
          # Tailor include patterns to files with monetary logic
          coverage report \
            --include="orders/models.py,orders/views.py,orders/utils/*.py,payments/services.py,payments/views.py,orders/services/*.py,engagement/services.py" \
            --fail-under=95

      - name: Upload coverage XML (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

